services:
  front:
    image: chl-front:dev
    container_name: chl_front
    build:
      context: ..
      dockerfile: .docker/frontend/Dockerfile
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=1
      - __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS=chl.front.local
    command:
      - sh
      - -lc
      - >
        [ -f package-lock.json ] || { echo "❌ Falta package-lock.json en /app"; exit 1; };
        if [ ! -d node_modules ] || [ ! -f .lockhash ] || [ "$(sha1sum package-lock.json | awk '{print $1}')" != "$(cat .lockhash 2>/dev/null)" ]; then
          npm ci && sha1sum package-lock.json | awk '{print $1}' > .lockhash;
        fi;
        npm run start -- --proxy-config proxy.conf.json --host 0.0.0.0 --port 4200 --hmr --poll=2000 --allowed-hosts=chl.front.local
    volumes:
      - ../frontend:/app
      - front_node_modules:/app/node_modules
    ports:
      - "4200:4200"
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.front.rule=Host(`chl.front.local`)
      - traefik.http.routers.front.entrypoints=web
      - traefik.http.services.front.loadbalancer.server.port=4200
    networks: [web]

volumes:
  front_node_modules:

networks:
  web:
    external: true
    name: web