services:
  front:
    image: chl-frontend:dev
    container_name: chl_front
    build:
      context: ..
      dockerfile: .docker/frontend/Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=1
      - NPM_CONFIG_PRODUCTION=false
      - __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS=chl.front.local
    command: >
      npm run start -- 
      --host 0.0.0.0 
      --port 4200 
      --hmr 
      --poll=2000
      --allowed-hosts=chl.front.local
    working_dir: /app
    volumes:
      - ../frontend:/app
      - /app/node_modules
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.front.rule=Host(`chl.front.local`)
      - traefik.http.routers.front.entrypoints=web
      - traefik.http.services.front.loadbalancer.server.port=4200
    networks:
      - web

networks:
  web:
    external: true
    name: web
