# docker-compose.yml
version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: pg-checklist
    environment:
      POSTGRES_USER: checklist
      POSTGRES_PASSWORD: checklist
      POSTGRES_DB: checklist_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U checklist"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  pgdata:
