spring:
  application:
    name: teamchecklist

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: false
    locations: classpath:db/migration

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false


server:
  port: 8080